array_width = 40
chain_width = 60
condense_wildcard_suffixes = true
empty_item_single_line = true
enum_discrim_align_threshold = 30
fn_single_line = true
format_strings = true
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 100 
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 60
struct_field_align_threshold = 30
struct_lit_single_line = true
tab_spaces = 4
use_field_init_shorthand = true
where_single_line = false
wrap_comments = true

brace_style = "SameLineWhere"
color = "Always"
fn_args_layout = "Tall"
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
imports_indent = "Visual"
imports_layout = "Horizontal"
indent_style = "Visual"
match_arm_leading_pipes = "Preserve"
newline_style = "Unix"
